input_file: "example_data/christmas_carol_intro.pdf"
output_folder: "example_data/"
text_to_text_model: "allenai/OLMoE-1B-7B-0924-Instruct-GGUF/olmoe-1b-7b-0924-instruct-q8_0.gguf"
text_to_speech_model: "OuteAI/OuteTTS-0.1-350M-GGUF/OuteTTS-0.1-350M-FP16.gguf"
text_to_text_prompt: |
 You are a playwright generating engaging and immersive dialogue for a radio drama in JSON format.
 The drama is based on the  provided context
 The script features the following characters:
 {SPEAKERS}
 Instructions:
 - Write compelling, emotionally rich dialogue that reflects the personalities of the characters and advances the story.
 - Stay true to the original themes and tone of the provided context, emphasizing character development and moral lessons.
 - Add interjections to enhance the radio drama's atmosphere.
 - Format the output as a JSON conversation.
 - Avoid repeating ideas already discussed
 - Mix up the order of the speakers
 - End appropriately after around 20 dialogue exchanges
  Example:
 {
  "Speaker 1": "Bah, humbug! Why would I care for Christmas?",
  "Speaker 2": "If I may, sir, Christmas is about kindness, something we could all use more of.",
  "Speaker 3": "Uncle Scrooge, Christmas is a time for joy and goodwill!",
  "Speaker 1": "Enough about kindness!",
 }
speakers:
  - id: 1
    name: Scrooge
    description: Scrooge is the miserly and skeptical protagonist. He dismisses the joys of Christmas and struggles to see beyond his greed and bitterness.
    voice_profile: male_1
  - id: 2
    name: Bob Cratchit
    description: Bob is a kind-hearted but underpaid employee. He represents humility and warmth despite his hardships.
    voice_profile: male_4
  - id: 3
    name: Fred
    description: Fred is cheerful and good-natured nephew, who believes in the spirit of Christmas.
    voice_profile: female_1

